name: inspiresearch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - flask=2.0.1
  - pillow=9.0.0
  - numpy=1.20.3
  - tensorflow=2.6.0
  - tqdm=4.62.3
  - werkzeug=2.0.1
  - faiss-cpu=1.7.2
  - pip=21.2.4
  - pip:
    - requests==2.26.0
